-- SESA Question Export
-- Paste into Neon SQL Editor and run

INSERT INTO question (test_type, question_content, created_at) VALUES ('Separation Anxiety Disorder', 'I would feel afraid of being on my own at home', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Separation Anxiety Disorder', 'I worry when I go to bed at night', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Separation Anxiety Disorder', 'I am afraid of being in a crowded place(like morning assembly, dining hall, house meetings, church service, entertainment)', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Separation Anxiety Disorder', 'I worry about being away from my parents', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Separation Anxiety Disorder', 'I feel scared if I have to sleep on my own', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Separation Anxiety Disorder', 'I have trouble going to school in the mornings because i feel nervous or afraid', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Separation Anxiety Disorder', 'I will often be scared if I had to stay away from home overnight', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Social Phobia', 'I worry when I think I have done poorly at something such as class test and examination', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Social Phobia', 'I feel worried when I have to take a class test', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Social Phobia', 'I feel worried when i think someone is angry with me', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Social Phobia', 'I worry that I will do badly at my school work', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Separation Anxiety Disorder', 'I worry I might look foolish in the eyes of others', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Social Phobia', 'I worry about making mistakes and being mocked', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Social Phobia', 'I worry what other people think of me', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Social Phobia', 'I feel afraid if I have to talk in front of my class', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Social Phobia', 'I feel afraid that I will make mistakes in front of people', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Generalised Anxiety Disorder', 'I worry about things', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Generalised Anxiety Disorder', 'I worry that something awful will happen to someone in my family', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Generalised Anxiety Disorder', 'I worry that bad things will happen to me', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Generalised Anxiety Disorder', 'I worry that something bad will happen', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Generalised Anxiety Disorder', 'I worry about what is going to happen', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Generalised Anxiety Disorder', 'I think about death', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Panic Disorder', 'When I have a problem, I get a funny feeling in my stomach', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Panic Disorder', 'I suddenly have difficulty breathing for no reason', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Panic Disorder', 'When I have a problem, my heart beats really fast', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Separation Anxiety Disorder', 'I suddenly start to tremble or shake when there is no reason for this', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Panic Disorder', 'After I have a problem, I feel shaky', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Panic Disorder', 'I get really scared for no reason at all', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Panic Disorder', 'I get dizzy or faint when there is no reason for this', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Panic Disorder', 'My heart suddenly starts to beat too quickly for no reason', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Panic Disorder', 'I get a scared feeling when there is no reason for that', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Obsessive Compulsive Disorder', 'I get bothered by bad or silly thoughts or pictures in my mind', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Obsessive Compulsive Disorder', 'I have to check that I have done things right (like the switch is off, or the door is locked)', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Obsessive Compulsive Disorder', 'I can''t seem to get bad or silly thoughts out of my head', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Obsessive Compulsive Disorder', 'I have to think of special thoughts (like numbers or words) to stop bad things from happening', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Obsessive Compulsive Disorder', 'I have to do some things over and over again (like washing my hands, cleaning or putting things in a certain order)', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Obsessive Compulsive Disorder', 'I have to do some things in just the right way to stop bad things from happening', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Major Depressive Disorder', 'I feel sad or empty', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Major Depressive Disorder', 'Nothing is much fun anymore', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Major Depressive Disorder', 'I have trouble sleeping', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Major Depressive Disorder', 'I have problems with my appetite', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Major Depressive Disorder', 'I have no energy for things', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Major Depressive Disorder', 'I feel guilty', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Major Depressive Disorder', 'I cannot think clearly', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Major Depressive Disorder', 'I feel worthless', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Major Depressive Disorder', 'I feel like I do not want to move', NOW());
INSERT INTO question (test_type, question_content, created_at) VALUES ('Major Depressive Disorder', 'I feel restless', NOW());
